# Generated by Django 6.0.5 on 2026-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
