# Generated by Django 6.0.5 on 2026-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_module', '0002_studynote_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
